### ISSUE TITLE
Kernel doesn't display anything.

### ISSUE THREAD

**Issue by luckboy** [l4ka/pistachio#10]
I compiled  kernel and user applications for x86-32 and ran under qemu. Used tools to compilation and launching:
gcc 4.6.3 and 4.4.7
binutils 2.22
qemu 1.0

I used qemu monitor to check what heppened. The eip register had value 0x0000000000403591 after launching of kernel. This addres was in memory area of pingpong.

**Comment by jkehne** [comment]
Did you check the serial console?

**Comment by luckboy** [comment]
I didn't check serial console.

**Comment by luckboy** [comment]
I did check serial console. It works! Kernel and pingpong displayed messages.
How do I enable vga console in kernel and user applications?

**Comment by jkehne** [comment]
For the kernel, try menuconfig -> Debugger -> Kernel Debugger Console (you want "Keyboard")
For userland, pass the option --without-comport to configure

I'm not sure though if the VGA console will work out of the box with qemu.

**Comment by luckboy** [comment]
Thank you. I come to it. VGA console works under qemu.

**Comment by jkehne** [comment]
Congratulations :)

**Comment by luckboy** [comment]
You can close this issue:) But I still have one problem that is described next issue.
