### ISSUE TITLE
TFTP protocol not working for network booting

### ISSUE THREAD

**Issue by ghost** [l4ka/pistachio#3]
Hello there,

I have not been able to boot pistachio over the network using TFTP. I have also tried with Pulsar and gPXE. Is this scenario supported in the current version of Pistachio?

Thanks.

**Comment by chelmuth** [comment]
Could you provide more information about your actual setup, what you expected to happen and what happened instead? Even an excerpt of the boot log may help. I used to boot Pistachio with gPXE and it worked.

**Comment by chelmuth** [comment]
Declaring the boot modules in reverse order seems to fix the mentioned problem, e.g.

```
module /debug/pistachio/core
module /debug/pistachio/sigma0
module /debug/pistachio/x86-kernel
chain /debug/pistachio/kickstart maxmem=256M
```

**Comment by jstoess** [comment]
Hi Amadeo,

I'm regularly booting pistachio via TFT, via grub. You'll need a netboot-able GRUB (eg. Grub netboot with legacy devices, or grub pxe).

-----Original Message-----
From: Amadeo [mailto:reply@reply.github.com] 
Sent: Thursday, January 19, 2012 8:23 PM
To: jstoess
Subject: [pistachio] TFTP protocol not working for network booting (#3)

Hello there,

I have not been able to boot pistachio over the network using TFTP. I have also tried with Pulsar and gPXE. Is this scenario supported in the current version of Pistachio?

Thanks.

---

Reply to this email directly or view it on GitHub:
https://github.com/l4ka/pistachio/issues/3
