### ISSUE TITLE
Bug at bswap64.

### ISSUE THREAD

**Issue by luckboy** [l4ka/pistachio#9]
The bswap64 function has the argument with incorrect type at kernel/src/arch/x86/x64/byteorder.h. This argument should have the u64_t type instead of the u32_t type.

**Comment by jkehne** [comment]
It looks like byteorder.h is not included anywhere. Do you need those functions for anything in particular? If not, I'll just remove the file.

**Comment by luckboy** [comment]
I just browsed this code. You don't have to remove this file. You can change type of argument of bswap64 (change u32_t to u64_t).

**Comment by jkehne** [comment]
I realize I can change the argument of bswap64 to fix the bug you reported. But if that function is not used anywhere, there is no point in dragging along dead code.
